title: DevOps Portfolio
description: Willkommen! Hier sind meine Projekte aus Cloud, CI/CD, Kubernetes, Monitoring und Automation.
show_downloads: false
github:
  is_project_page: true
google_analytics:
theme: jekyll-theme-architect
