title: Ismail Agac DevOps & Cloud Portfolio
description: Willkommen! Hier sind meine Projekte aus Cloud, CI/CD, Kubernetes, Monitoring und Automation.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
